### ISSUE TITLE
product translation w/ spree_i18n extension

### ISSUE THREAD

**Issue by james075** [spree-contrib/spree_drop_ship#53]
Hi, 

How could I authorize suppliers access to their product translation with spree_i18n extension from the supplier backend? So far only admins can do that.

Thanks.

**Comment by simo163** [comment]
I am running into the same issue. The problem is my app accepts several stores, each store has their own products. How can I authorize the products translations for each store. Let suppose store S1 has product P1 and store S2 has product P1, how would be possible that S1 cannot modify P2 translations and viceversa? Thanks
